### PR TITLE
add a factory method for AnyType

### PR DESCRIPTION
**Pull request by smilingleo**
instead of `new AnyType<MyType>(){}` everywhere, just use `Any.type()`

### CODE REVIEW

**Comment by Randgalt** [comment]
Wow - I'm surprised that works. I thought that the only way to get the semi-reified type was the way I did it. I'll need to test this in some edge cases.

**Comment by Randgalt** [comment]
This does not work. Try this:

```java
Any<List<String>> anyList1 = Any.type();
Any<List<String>> anyList2 = new Any<List<String>>(){};
System.out.println(anyList1.getRawType());
System.out.println(anyList2.getRawType());
```

There's no workaround that I know of.

**Comment by smilingleo** [comment]
Oops, poor Java type system. Let me see if there I can find a workaround.

**Comment by Randgalt** [comment]
It's erasure. A 1000 deaths for those who decided erasure was OK.

**Comment by smilingleo** [comment]
no workaround, :(

**Comment by Randgalt** [comment]
There's a special place in Hell for erasure :(

**Pull request closed without merging**
